---

- hosts: webservers
  become: yes

  tasks:
    - name: print OS info
      debug:
        msg: >-
          This server is running the {{ ansible_distribution }} distribution,
          version {{ ansible_distribution_version }} {{ ansible_distribution_release }},
          in the {{ ansible_os_family }} OS family.
