---
- hosts: localhost
  connection: local

  tasks:
  - name: include variables
    include_vars:
      file: roles/new-linode_create/vars/main.yml

  - name: pip install linode_api4
    pip:
      name: linode_api4

  - name: Ensure linode is missing (delete if present)
    linode_v4:
      label: "{{ linode_label }}"
      access_token: "{{ maximum_ethics_linode_token }}"
      state: absent

  # https://docs.ansible.com/ansible/latest/modules/known_hosts_module.html
  - name: Remove hostname from ~/.ssh/known_hosts
    known_hosts:
      name: '{{ linode_label }}'
      state: absent

  - name: Remove lines with unwanted occurrences of hostname
    lineinfile:
      path: "{{ inventory_directory }}/hosts"
      regexp: '^{{ linode_label }}$'
      state: absent
    become: true

# TODO: add task for manual confirmation
# We don't want to destroy servers by accident
# https://github.com/sunrisemovement/devops/issues/3
