---

- hosts: localhost
  become: yes
  connection: local

  roles:
    - new-linode_create

- hosts: new
  gather_facts: no

  roles:
    - new-linode_initiate-users

- hosts: new
  become: yes

  roles:
    - new-linode_harden
