---

- hosts: sunrise
  become: yes
  vars:
    domain_name: houston.sunrisemovement.org
    site_title: Sunrise Movement Houston
    git_theme: true
    git_repo: https://github.com/sunrisemovement/hugo-black-and-light-theme.git
    theme_name: black-and-light

  tasks:
  - name: update Caddyfile
    copy: src=../Caddyfile dest=/etc/caddy/Caddyfile
  - name: reload caddy
    service:
      name: caddy
      state: reloaded
  - name: Create new Hugo site
    command: hugo new site /srv/{{ domain_name }}
    args:
      creates: /srv/{{ domain_name }}
  - name: clone git theme
    git:
      repo: "{{ git_repo }}"
      dest: /srv/{{ domain_name }}/themes/{{ theme_name }}
    when: git_theme
  - name: create config.toml file from template
    template:
      src: ../config.toml
      dest: /srv/{{ domain_name }}/config.toml
      owner: www-data
      group: www-data
  - name: generate Hugo site again
    command: hugo
    args:
      chdir: /srv/{{ domain_name }}
      creates: /srv/{{ domain_name }}/public
  - name: make www-data owner of everything in the damn directory
    file:
      path: /srv/{{ domain_name }}
      owner: www-data
      group: www-data
      recurse: yes
