---
# TIP: add the subdomain's A + AAAA records to the Linode control panel first!
# Otherwise Let's Encrypt can't verify your certificates

- hosts: attenborough
  become: yes
  vars:
    subdomain: ri
    domain_name: sunrisemovement.dev
    git_repo: https://github.com/michaelkearney55/ri.sunrisemovement.org.git

  tasks:
  - name: install packages
    apt:
      name: '{{ item }}'
    loop:
      - git
      - php-fpm
  # - name: update Caddyfile
  #   copy:
  #     src: roles/sunrise/files/Caddyfile
  #     dest: /etc/caddy/Caddyfile
  #     owner: root
  #     group: root
  #     mode: '0644'
  #   notify:
  #     - reload caddy
  - name: include variables (need admin e-mail)
    include_vars:
      file: roles/sunrise/vars/main.yml
  - name: install Caddyfile from template
    template:
      src: roles/sunrise/templates/Caddyfile.j2
      dest: /etc/caddy/Caddyfile
      owner: root
      group: root
      mode: '0644'
    notify:
      - reload caddy
  - name: clone git repository for subdomain
    git:
      repo: "{{ git_repo }}"
      dest: /srv/{{ domain_name }}/{{ subdomain }}/public/
    notify:
      - make www-data owner
  #   when: subdomain is defined
  # - name: clone git repository
  #   git:
  #     repo: "{{ git_repo }}"
  #     dest: /srv/{{ domain_name }}/public/
  #   when: subdomain is not defined

  handlers:
  - name: reload caddy
    service:
      name: caddy
      state: reloaded
  - name: make www-data owner #of everything in the darn directory
    file:
      path: /srv/{{ domain_name }}/{{ subdomain }}
      owner: www-data
      group: www-data
      recurse: yes
