- hosts: all
  become: yes
  tasks:
  - name: update apt sources (if we haven't lately) + upgrade packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: safe
    when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'

  - name: Run the equivalent of "pacman -Syu", updating sources and packages
    pacman:
      update_cache: yes
      upgrade: yes
    when: ansible_os_family == 'Archlinux'
