---

- hosts: sunrise
  vars:
    user_password: $6$3l5huhnkBaqcAw$T3VCnf5ydNbXPp0bWrb7dYyNanLwHDBAX2hr1VDw6VFM8GLYKKKl7MY7eUxOc1yo9AfNtZ2uWInabJBE.zen91

  tasks:
  - name: "Add a limited user account"
    user:
      name: "{{ normal_user_name }}"
      password: "{{ user_password }}"
      shell: /bin/bash
      groups: sudo
    tags: user_password
  - name: "Add remote authorized key to allow future passwordless logins"
    authorized_key:
      user: "{{ normal_user_name }}"
      key: "{{ lookup('file', '/Users/{{ normal_user_name }}/.ssh/id_rsa.pub') }}"
    tags: authorized_key

# automate step where I delete the entry from ~/.ssh/known_hosts
