os_packages:
  - base-devel # needed for AUR
  - fd # find alternative
  - which # to find where executables are installed
  - rsync # dependency for "synchronize" Ansible module
  - go # needed to build Caddy from source or use Hugo modules
# Caddy is currently in Community-Testing:
# https://archlinux.org/packages/community-testing/x86_64/caddy/
# I manually enabled that repo:
# https://joshtronic.com/2019/08/19/how-to-install-packages-from-testing-on-arch-linux/
# if it doesn't come out of testing soon we should write a play to do this
  - caddy # web server https://caddyserver.com/
  - hugo # static site generator https://gohugo.io/
  - tldr # python client, use until tealdeer is available

sudoing_group: wheel
web_server_user: caddy

# Set this to true to use the vars in local_tls.yml
local_tls: false
# caddy_conf_autosave_dir: /srv/http/.config/caddy

# https://stackoverflow.com/questions/17570658/how-to-find-my-php-fpm-sock
# check /etc/php/php-fpm.d/www.conf for location of unix socket
# should be line like "listen = /run/php-fpm/php-fpm.sock"
php_fpm_unix_socket: /run/php-fpm/php-fpm.sock
php_fpm_service_name: php-fpm
