os_packages:
  - base-devel # needed for AUR
  - exa # ls alternative
  - fd # find alternative
  - which # to find where executables are installed
  - rsync # dependency for "synchronize" Ansible module
  - go # needed to build Caddy from source
  - hugo # static site generator https://gohugo.io/
aur_packages:
  - yay # preferred AUR helper
  - micro # terminal-based text editor
  - caddy-bin # hope this makes it back into the official repos someday
  - tealdeer # tldr client

sudoing_group: wheel
web_server_user: caddy

local_tls: false
# caddy_conf_autosave_dir: /srv/http/.config/caddy

# https://stackoverflow.com/questions/17570658/how-to-find-my-php-fpm-sock
# check /etc/php/php-fpm.d/www.conf for location of unix socket
# should be line like "listen = /run/php-fpm/php-fpm.sock"
php_fpm_unix_socket: /run/php-fpm/php-fpm.sock
php_fpm_service_name: php-fpm
