os_packages:
  - base-devel # needed for AUR
  - dust # visualize disk space use
  - eza # ls alternative
  - fd # find alternative
  - tealdeer # A fast tldr client in Rust
  - chezmoi # bring your personal dotfiles to the server
  - fastfetch # show OS details
  - rsync # dependency for "synchronize" Ansible module
  - php
  - php-fpm # serve PHP sites via FastCGI
  - go # needed to build Caddy from source or use Hugo modules
  - caddy # web server https://caddyserver.com/
  - hugo # static site generator https://gohugo.io/
  - nodejs # needed for Bookshop

uninstall_packages:
  - linux-firmware # Unnecessary on Linode, needed on bare metal tho

web_server_user: caddy

caddy_binary_location: /usr/bin/caddy

# https://stackoverflow.com/questions/17570658/how-to-find-my-php-fpm-sock
# check /etc/php/php-fpm.d/www.conf for location of unix socket
# should be line like "listen = /run/php-fpm/php-fpm.sock"
php_fpm_unix_socket: /run/php-fpm/php-fpm.sock
php_fpm_service_name: php-fpm
