os_packages:
  - base-devel # needed for AUR
  - fd # find alternative
  - which # to find where executables are installed
  - rsync # dependency for "synchronize" Ansible module
  - php
  - php-fpm # serve PHP sites via FastCGI
  - go # needed to build Caddy from source or use Hugo modules
  - caddy # web server https://caddyserver.com/
  - hugo # static site generator https://gohugo.io/
  - tealdeer # A fast tldr client in Rust

web_server_user: caddy

# https://stackoverflow.com/questions/17570658/how-to-find-my-php-fpm-sock
# check /etc/php/php-fpm.d/www.conf for location of unix socket
# should be line like "listen = /run/php-fpm/php-fpm.sock"
php_fpm_unix_socket: /run/php-fpm/php-fpm.sock
php_fpm_service_name: php-fpm
