hugo_deb_url: https://github.com/gohugoio/hugo/releases/download/v0.67.0/hugo_0.67.0_Linux-64bit.deb
hugo_sites:
  - title: Sunrise Movement Philadelphia
    domain: sunrisemovement.dev
    subdomain: philadelphia
    theme_repo: https://github.com/sunrisemovement/hugo-black-and-light-theme.git
    theme_name: black-and-light
