common_packages:
  - fish # Nelson's favorite shell
  - bat # cat alternative
  - exa # ls alternative
  - mosh # better than SSH over crappy/mobile connections
  - git # check out git repositories
  - php
  - php-fpm # serve PHP sites via FastCGI
  - acl # allows becoming unprivileged user (for git clone)
  - micro # terminal-based text editor
  - tldr # use until tealdeer is available
  - neofetch # show OS details

default_pass: "$6$mysecretsalt$KX2mLFmN1x9gF/urPk7EpzaMJMcY4yoFetMlQw0W9Lm2MJZ8cVI/7dk25PVyb6cLx7IUwTxON5HucMHOdsP.Y0"
admin_email: skyfaller@gmail.com

users:
  - name: wilsonbr
    password: "{{ default_pass }}"
    shell: /usr/bin/fish
    sshKey:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMSoD1EE/VdDb9mBYDsebsIVowqhfvNWYhe2YBcfNeTo wilsonbr@cthulu2
  - name: nelson
    password: "{{ default_pass }}"
    shell: /usr/bin/fish
    sshKey:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJcoG9tZKULXW2IQ+5MsZ3vgUBJ5C3uDbbG381S1Cjdl nelson@Valence.local
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGnUmCzUu/jrZz+T5rVTEJQ73zobj+CixKJS2N9jMkhz nelson@annalise
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKH1YH796hxWQu5B/mHwU6nfG1fDDAO8FtI3UpwcbbTs nelson@cordelia

test_domain: maximumethics.dev
test_subdomain: test
building_caddy: false
caddyfile_name: Caddyfile.j2

handcoded_websites:
  - subdomain: www
    domain_name: sunrisepvd.com
    git_repo: https://github.com/sunriseprovidence/sunrisepvd.com.git

hugo_deb_url: https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_extended_0.87.0_Linux-64bit.deb
hugo_sites:
  - title: Maximum Ethics
    domain: maximumethics.dev
    subdomain: www
    content_repo: https://git.sr.ht/~skyfaller/maximum-ethics-content
    # theme_repo: https://git.sr.ht/~skyfaller/maxethics-hugo
    # theme_name: maxethics-hugo
  - title: Nelson's minimal Hugo website
    domain: pavlosky.net
    subdomain: nelson
    content_repo: https://git.sr.ht/~skyfaller/nelson-site
  - title: Oahspe Sales
    domain: oahspesales.com
    subdomain: www
    content_repo: https://git.sr.ht/~skyfaller/oahspesales.com
