common_packages:
  - acl # allows becoming unprivileged user (for git clone)
  - bat # cat alternative
  - exa # ls alternative
  - fish # Nelson's favorite shell
  - git # check out git repositories
  - micro # terminal-based text editor
  - mosh # better than SSH over crappy/mobile connections
  - neofetch # show OS details
  - ripgrep # recursively searches directories for a regex
  - zoxide # smarter cd command - navigate filesystem faster
  - unzip # make unarchive work

default_pass: "$6$mysecretsalt$KX2mLFmN1x9gF/urPk7EpzaMJMcY4yoFetMlQw0W9Lm2MJZ8cVI/7dk25PVyb6cLx7IUwTxON5HucMHOdsP.Y0"
admin_email: skyfaller@gmail.com

users:
  - name: wilsonbr
    password: "{{ default_pass }}"
    shell: /usr/bin/fish
    sshKey:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPAP3OixTq8fc34Im8hWBG6JjElOxskPsnO5UmgwDHyZ wilsonbr@CthuluPopOs
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM5luwrRmBK+XE2zyy3MhxaaP6/Ua8yhIHwIgYJvBN1d wilsonbr@woody
  - name: nelson
    password: "{{ default_pass }}"
    shell: /usr/bin/fish
    sshKey:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJcoG9tZKULXW2IQ+5MsZ3vgUBJ5C3uDbbG381S1Cjdl nelson@Valence.local
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGnUmCzUu/jrZz+T5rVTEJQ73zobj+CixKJS2N9jMkhz nelson@annalise
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKH1YH796hxWQu5B/mHwU6nfG1fDDAO8FtI3UpwcbbTs nelson@cordelia
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBr1tfGGpLk2AqGUFSETR8/3OGszYgATSeSP+FX9rkCA nelson@judy
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO+0WMGEhUyreBZA0CZ4Bim54VwP9K5o5t0zOC4ki5YN nelson@melly
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOs89w1+6svcRASva821bysSFAG2qFO93qwmco3Fj/U7 u0_a314@localhost
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA3Ktn0c3pSic0v1rtaRrxJ2O+9XbuyNawjj91A/D3Wf GitHub key for nelson@bobbie

test_domain: maximumethics.dev
test_subdomain: test
building_caddy: false
caddyfile_name: Caddyfile.j2

handcoded_websites:
  - subdomain: www
    domain_name: sunrisepvd.com
    git_repo: https://github.com/sunriseprovidence/sunrisepvd.com.git

hugo_deb_url: https://github.com/gohugoio/hugo/releases/download/v0.92.1/hugo_extended_0.92.1_Linux-64bit.deb
hugo_sites:
  - title: Maximum Ethics
    domain: maximumethics.dev
    subdomain: www
    content_repo: https://git.sr.ht/~skyfaller/maximum-ethics-content
    # theme_repo: https://git.sr.ht/~skyfaller/maxethics-hugo
    # theme_name: maxethics-hugo
  - title: Bookshop Demo
    domain: maximumethics.dev
    subdomain: bookshop
    content_repo: https://github.com/CloudCannon/hugo-bookshop-starter/
  - title: Nelson's minimal Hugo website
    domain: pavlosky.net
    subdomain: nelson
    content_repo: https://git.sr.ht/~skyfaller/nelson-site
  - title: Oahspe Sales
    domain: oahspesales.com
    subdomain: www
    content_repo: https://git.sr.ht/~skyfaller/oahspesales.com
  - title: McFadden Mental Health
    domain: robertmcfaddenmd.com
    subdomain: www
    content_repo: https://git.sr.ht/~skyfaller/robertmcfaddenmd.com

static_wp_sites:
  - subdomain: static
    domain_name: skyfaller.space
  - subdomain: static
    domain_name: stairball.club
