common_packages:
  - fish # Nelson's favorite shell
  - bat # cat alternative
  - mosh # better than SSH over crappy/mobile connections
  - git # check out git repositories
  - php
  - php-fpm # serve PHP sites via FastCGI
  - acl # allows becoming unprivileged user (for git clone)

default_pass: "$6$mysecretsalt$KX2mLFmN1x9gF/urPk7EpzaMJMcY4yoFetMlQw0W9Lm2MJZ8cVI/7dk25PVyb6cLx7IUwTxON5HucMHOdsP.Y0"
admin_email: skyfaller@gmail.com

users:
  - name: wilsonbr
    password: "{{ default_pass }}"
    shell: /bin/bash
    sshKey:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMSoD1EE/VdDb9mBYDsebsIVowqhfvNWYhe2YBcfNeTo wilsonbr@cthulu2
  - name: nelson
    password: "{{ default_pass }}"
    shell: /usr/bin/fish
    sshKey:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJcoG9tZKULXW2IQ+5MsZ3vgUBJ5C3uDbbG381S1Cjdl nelson@Valence.local
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGnUmCzUu/jrZz+T5rVTEJQ73zobj+CixKJS2N9jMkhz nelson@annalise
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKg8msSyWifH18t2JmqV36UlarCg+HSHQ8LIXC3qykgC Nelson's Pixel 3a XL
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKH1YH796hxWQu5B/mHwU6nfG1fDDAO8FtI3UpwcbbTs nelson@cordelia
sudoing_group: wheel

# vars for caddy.yml
caddy_storage_dir: '{{ webserver_user_registered.home }}/.local/share/caddy'
caddy_conf_autosave_dir: '{{ webserver_user_registered.home }}/.config/caddy'
test_domain: maximumethics.dev
test_subdomain: www
building_caddy: false
caddyfile_name: Caddyfile.j2

handcoded_websites:
  - subdomain: www
    domain_name: sunrisepvd.com
    git_repo: https://github.com/sunriseprovidence/sunrisepvd.com.git

hugo_deb_url: https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_0.75.1_Linux-64bit.deb
hugo_sites:
  - title: Sunrise Movement Philadelphia
    domain: sunrisemovement.dev
    subdomain: philadelphia
    theme_repo: https://github.com/sunrisemovement/hugo-black-and-light-theme.git
    theme_name: black-and-light
  - title: Sunrise Movement Houston
    domain: sunrisemovement.dev
    subdomain: houston
    theme_repo: https://github.com/sunrisemovement/hugo-black-and-light-theme.git
    theme_name: black-and-light
