# tasks on remote server once it has been created, as your own user #
- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
  - restart ssh
# change passwords last, you can't do anything else afterwards!
  - force change password
# note that handlers are executed in the order they are written down, NOT in the order they are notified
# https://stackoverflow.com/questions/35130051/order-of-notify-handlers

- name: Install PAM on Alpine Linux
  package:
    name: openssh-server-pam
    state: present
  when: ansible_os_family == 'Alpine'

- name: Make sure PAM is enabled to enforce password change
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UsePAM"
    insertafter: '^#UsePAM '
    line: "UsePAM yes"
    state: present
  notify:
  - restart ssh
  - force change password

# Switch to Linode's latest kernel to improve security and ensure all functions work.
