# - name: include testing vars file when testing
#   include_vars: Ubuntu.yml
#   when: ansible_distribution == 'Ubuntu'
#   tags: always

- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Add limited user accounts for all Sunrise sysadmins
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
    groups: "{{ sudoing_group }}"
    update_password: on_create
  loop: "{{ users }}"
  tags: user_password

# - name: Add ssh keys for all Sunrise sysadmins
#   authorized_key:
#     user: "{{ item.name }}"
#     key: "{{ item.sshKey }}"
#   loop: "{{ users }}"
#   tags: authorized_keys

- name: Add ssh keys for all Sunrise sysadmins
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
# old syntax for doing loop with subelements:
# https://docs.ansible.com/ansible/latest/plugins/lookup/subelements.html
  # with_subelements:
  #   - "{{ users }}"
  #   - sshKey
# new syntax described here:
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-subelements
  loop: "{{ users|subelements('sshKey') }}"
  tags: authorized_keys

- name: update apt sources + upgrade packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe
  tags: updategrade
  when: ansible_os_family == 'Debian'

- name: update sources + upgrade packages
  pacman: 
    update_cache: yes
    upgrade: yes
  tags: updategrade
  when: ansible_os_family == 'Archlinux'

# first, put local_hostname in ansible inventory
- name: set system's hostname
  hostname:
    name: "{{ local_hostname }}"
  tags: hostname
- name: print hostname
  debug:
    msg: Inventory item {{ inventory_hostname }} has hostname {{ ansible_hostname }}
    verbosity: 1
  tags: hostname

- name: print datetime before setting timezone
  debug:
    var: ansible_date_time
    verbosity: 1
  tags: timezone
# to get list of possible timezones, run "timedatectl list-timezones"
- name: set timezone to NYC
  timezone:
    name: America/New_York
    # name: America/Los_Angeles
  tags: timezone
  notify: 
    - restart cron + print time

- name: configure firewall using UFW
# Maybe I should use iptables directly, but it's easier/simpler to set up UFW
# persistently using Ansible, so let's try it for now.
  import_tasks: ufw.yml
  tags: ufw

# TODO: fail2ban?

- name: install mosh # better than SSH over crappy/mobile connections
  package:
    name: mosh
  tags: mosh
- name: allow mosh traffic through ufw
  ufw:
    rule: allow
    port: 60000:61000
    proto: udp
  tags: mosh

# - name: customize the message of the day when logging in to the server
#   import_tasks: motd.yml
#   tags: motd

- name: print OS info
  debug: 
    msg: This server is running the {{ ansible_distribution }} distribution in the {{ ansible_os_family }} OS family.
    verbosity: 1
  tags: caddy_v2
- name: setup Caddy V2 web server on Arch Linux
  import_tasks: caddy.yml
  tags: caddy_v2

- name: set up some handcoded websites
  import_tasks: new_handcoded.yml
  tags: new_handcoded

# Hugo playbook doesn't work yet
# - name: set up Hugo websites
#   import_tasks: hugo.yml
#   tags: hugo

# TODO: set up Longview - record and view stats, data to help diagnose problems

# TODO: set up e-mail so unattend-upgrades, Wordpress etc. can mail you
# - name: install postfix
#   apt:
#     name: postfix

# TODO: install Wordpress