- name: Make sure 00-header is my preferred version
  copy:
    src: 00-header
    dest: /etc/update-motd.d/00-header
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: ansible_distribution == 'Ubuntu'
  notify:
  - update motd-news service

- name: make 10-help-text unexecutable (remove help text)
  file:
    path: /etc/update-motd.d/10-help-text
    mode: "u=rw,g=r,o=r"
  when: ansible_distribution == 'Ubuntu'
  notify:
  - update motd-news service

- name: ensure 50-help-text is executable
  file:
    path: /etc/update-motd.d/50-motd-news
    mode: "u=rwx,g=rx,o=rx"
  when: ansible_distribution == 'Ubuntu'
  notify:
  - update motd-news service
# https://raymii.org/s/tutorials/Disable_dynamic_motd_and_motd_news_spam_on_Ubuntu_18.04.html
# Unfortunately motd-news now refuses to start if 50-motd-news is unexecutable:
# https://bugs.launchpad.net/ubuntu/+source/base-files/+bug/1803601
# So setting ENABLED=0 seems like the best option
- name: Disable Ubuntu commercial news
  lineinfile:
    path: /etc/default/motd-news
    regexp: '^ENABLED='
    line: ENABLED=0
  when: ansible_distribution == 'Ubuntu'
  notify:
  - update motd-news service

- name: Ensure your_ip.sh is installed, telling you your IP on login
  copy:
    src: your_ip.sh
    dest: /etc/profile.d/your_ip.sh