- name: Make sure 00-header is my preferred version
  copy:
    src: 00-header
    dest: /etc/update-motd.d/00-header
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: ansible_distribution == 'Ubuntu'
  notify:
  - update motd-news service

- name: make 10-help-text unexecutable (remove help text)
  file:
    path: /etc/update-motd.d/10-help-text
    mode: "u=rw,g=r,o=r"
  when: ansible_distribution == 'Ubuntu'
  notify:
  - update motd-news service

- name: Disable Ubuntu commercial news
  lineinfile:
    path: /etc/default/motd-news
    regexp: '^ENABLED='
    line: ENABLED=0
  when: ansible_distribution == 'Ubuntu'
  notify:
  - update motd-news service

- name: Ensure your_ip.sh is installed, telling you your IP on login
  copy:
    src: your_ip.sh
    dest: /etc/profile.d/your_ip.sh