---
# TIP: add the subdomain's A + AAAA records to the Linode control panel first!
# Otherwise Let's Encrypt can't verify your certificates

- name: install Caddyfile from template
  template:
    src: '{{ caddyfile_name }}'
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload caddy

- name: create srv directory if it doesn't exist
  file:
    path: /srv/{{ item.domain_name }}/{{ item.subdomain }}
    state: directory
    mode: 0755
    owner: '{{ web_server_user }}'
    group: '{{ web_server_user }}'
  loop: '{{ handcoded_websites }}'

- name: clone git repository for subdomain
  git:
    repo: '{{ item.git_repo }}'
    dest: /srv/{{ item.domain_name }}/{{ item.subdomain }}/public/
# Let's include parameters for sites that have them, and ignore them for sites that don't
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#defaulting-undefined-variables
    version: '{{ item.version | default(omit) }}'
    depth: '{{ item.depth | default(omit) }}'
  loop: '{{ handcoded_websites }}'
  become: yes
  become_user: '{{ web_server_user }}'
  tags: hand_git

- name: start and enable php-fpm service
  service:
    name: '{{ php_fpm_service_name }}'
    state: started
    enabled: yes