---
# TIP: add the subdomain's A + AAAA records to the Linode control panel first!
# Otherwise Let's Encrypt can't verify your certificates
- name: install packages
  apt:
    name: '{{ item }}'
  loop:
    - git
    - php-fpm
    - acl # allows becoming unprivileged user (for git clone)

- name: install Caddyfile from template
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload caddy

- name: create srv directory if it doesn't exist
  file:
    path: /srv/{{ item.domain_name }}/{{ item.subdomain }}
    state: directory
    mode: 0755
    owner: '{{ web_server_user }}'
    group: '{{ web_server_user }}'
  loop: "{{ handcoded_websites }}"

- name: clone git repository for subdomain
  git:
    repo: "{{ item.git_repo }}"
    dest: /srv/{{ item.domain_name }}/{{ item.subdomain }}/public/
  loop: "{{ handcoded_websites }}"
  become: yes
  become_user: '{{ web_server_user }}'
  tags: hand_git