- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs ppa for apt repo"
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ linux_distro }} main"
    update_cache: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present
